spring:
  application:
    name: eurake

server:
  port: 8762

eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#endpoints:
#  sensitive: true

