#devtools:
#  livereload:
#    enabled: true #是否支持livereload
#    port: 35729
#  restart:
#    enabled: true #是否支持热部署

spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true