spring:
  datasource:
#      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
      url: jdbc:mysql://rm-wz939g2zz921yd9rjo.mysql.rds.aliyuncs.com:3306/mytabis-redis?characterEncoding=utf8&useSSL=true
      username: root
      password: Jack123!
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    #redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其它数据库冲突
#    database: 3
    #redis服务器地址（默认为localhost)
#    host: localhost
#    host: r-wz931bdcdfb58e74.redis.rds.aliyuncs.com
    host: 39.108.137.74
    #redis端口（默认为6379)
#    port: 6379
    #redis访问密码
    password: 123456
    #redis连接超时时间(单位为毫秒）
    timeout: 0
    #redis连接池配置
    pool:
      #最大可用连接数(默认为8，负数表示无限）
      max-active: 8
      #最大空闲连接数(默认为8，负数表示无限)
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
       # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1


logging:
  config: classpath:log4j2.xml
#debug: true

mybatis:
  #配置方式1
  #config-location: classpath:mybatis-config.xml
  #配置方式2
  # 配置映射类所在包名
  type-aliases-package: com.demo.redis.dao.entity
  # 配置mapper xml文件所在路径
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
