spring:
  data:
    mongodb:
#      uri: mongodb://root:aixiangdao%4088@dds-wz946c0849dabfd4-pub.mongodb.rds.aliyuncs.com:3717/admin

#      host: dds-wz9237912b216244-pub.mongodb.rds.aliyuncs.com
#      port: 3717
#      database: testdb
#      username: testuser
#      password: testpassword

      host: 127.0.0.1
      port: 27017

