spring:
  data:
    mongodb:
#      uri: mongodb://root:Jack123!@dds-wz9528547cfc95141.mongodb.rds.aliyuncs.com:3717/test
      uri: mongodb://localhost/test
#      host: localhost
      username:
      password:
#      database: