

spring:
  data:
    mongodb:
      uri: mongodb://root:aixiangdao%4088@dds-wz946c0849dabfd4-pub.mongodb.rds.aliyuncs.com:3717/admin
#      uri: mongodb://localhost/test
#      host: localhost
#      username:
#      password:
server:
  port: 8081
#      database: