spring:
  application:
    name: mybatis
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

