spring:
    datasource:
        url: jdbc:mysql://rm-wz939g2zz921yd9rjo.mysql.rds.aliyuncs.com:3306/ch8_4-transactional?characterEncoding=utf8&useSSL=true
        password: Jack123!
        username: root
    jackson:
        serialization:
            indent_output: true
    jpa:
        hibernate:
        show-sql: true
