
spring:
  datasource:
#    schema: classpath:schema.sql
#    data: classpath:data.sql
    url: jdbc:h2:mem:test

  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 7001

debug: true

logging:
  config: classpath:logback.xml
  path: /ilike/logs/spring-data-jpa
