spring:
  datasource:
    driver-class-name:  org.h2.Driver
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
