spring:
  application:
    name: mybatis
  datasource:
    driver-class-name:  org.h2.Driver
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#
#endpoints:
#  sensitive: true
