server:
  port: 8040


spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


zuul:
  ignored-services: '*'
  routes:
    user-route:
      path: /**/mybatis/**
      service-id: mybatis
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

debug: true

