debug: true

spring:
    datasource:
      url: jdbc:h2:mem:test
    jackson:
        serialization:
            indent_output: true
    jpa:
        hibernate:
        show-sql: true
    h2:
      console:
        enabled: true
