spring:
  application:
    name: admin-client
  boot:
    admin:
      url: http://localhost:9999
      username: admin       #These two are needed so that the client
      password: 123456   #can register at the protected server api

management:
  security:
    enabled: false #can access the proteceted client endpoints
