

debug: true

spring:
    data:
        rest:
            basePath: /api
    datasource:
      url: jdbc:mysql://rm-wz939g2zz921yd9rjo.mysql.rds.aliyuncs.com:3306/gzh?characterEncoding=UTF-8&useSSL=true
      username: root
      password: Jack456!
    jackson:
        serialization:
            indent_output: true
    jpa:
      hibernate:
        ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true

server:
  port: 8082
