debug: true

spring:
    data:
        rest:
            base-path: /api
    datasource:
      driver-class-name:  org.h2.Driver
      url: jdbc:h2:mem:test
    jackson:
        serialization:
            indent_output: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    h2:
      console:
        enabled: true
