spring:
    datasource:
      driver-class-name:  org.h2.Driver
      platform: h2
      schema: classpath:schema.sql
      data: classpath:data.sql
    jackson:
        serialization:
            indent_output: true
    jpa:
        show-sql: true

    spring:
        redis:
            database: 0
            host: 172.31.19.222
            password: ''
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            port: 6379
            timeout: 0

